# esp_codec_dev — vendored from Espressif example for this board.
# Compiled from source to match our SPIRAM/alignment settings.

idf_component_register(
    SRCS
        "esp_codec_dev.c"
        "esp_codec_dev_vol.c"
        "esp_codec_dev_if.c"
        "audio_codec_sw_vol.c"
        "platform/audio_codec_gpio.c"
        "platform/audio_codec_ctrl_i2c.c"
        "platform/audio_codec_data_i2s.c"
        "platform/audio_codec_ctrl_spi.c"
        "platform/esp_codec_dev_os.c"
        "device/es8311/es8311.c"
    INCLUDE_DIRS
        "include"
        "interface"
        "device/include"
    PRIV_INCLUDE_DIRS
        "device/priv_include"
    REQUIRES
        driver
    PRIV_REQUIRES
        freertos
)
