/**
 * test_combat_determinism.c — Combined PRNG+CRC32 determinism tests
 * (Phase B: FEATURE RED).
 *
 * Constitution Priority 0 enforcement: this test proves that the core
 * deterministic math pipeline (PRNG → value stream → CRC32 hash) produces
 * identical output on every architecture and every run.
 *
 * DET-NT-4: 10,000 PRNG values from seed=1, hashed via CRC32, must equal
 *           the frozen literal 0x7B1900A6.
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "test_assert.h"
#include "prng.h"
#include "crc32.h"

/* ---------------------------------------------------------------------------
 * _Static_assert: type widths (DET-NT-1)
 * These enforce that the host architecture matches the ESP32-S3 target.
 * ---------------------------------------------------------------------------*/
_Static_assert(sizeof(uint8_t)  == 1u, "uint8_t  must be 1 byte");
_Static_assert(sizeof(uint16_t) == 2u, "uint16_t must be 2 bytes");
_Static_assert(sizeof(uint32_t) == 4u, "uint32_t must be 4 bytes");
_Static_assert(sizeof(int8_t)   == 1u, "int8_t   must be 1 byte");
_Static_assert(sizeof(bool)     == 1u, "bool     must be 1 byte");

/* ---------------------------------------------------------------------------
 * DET-NT-4: 10,000-iteration PRNG stream CRC32 hash.
 *
 * Algorithm:
 *   1. Seed PRNG with 1.
 *   2. Generate 10,000 uint32_t values.
 *   3. Store each value as 4 little-endian bytes in a 40,000-byte buffer.
 *   4. CRC32 the entire buffer.
 *   5. Assert the hash equals the pre-computed frozen literal.
 *
 * Frozen expected hash: 0x7B1900A6
 * (generated by reference Python implementation, pinned here permanently)
 * ---------------------------------------------------------------------------*/
static void test_10k_prng_crc32_hash(void)
{
    /* 40,000-byte static buffer — no heap allocation (embedded constraint) */
    static uint8_t buf[10000u * 4u];

    fq_prng_t rng;
    fq_prng_init(&rng, 1u);

    for (uint32_t i = 0u; i < 10000u; i++) {
        uint32_t v = fq_prng_next(&rng);
        /* Store as little-endian bytes */
        buf[i * 4u + 0u] = (uint8_t)((v >>  0u) & 0xFFu);
        buf[i * 4u + 1u] = (uint8_t)((v >>  8u) & 0xFFu);
        buf[i * 4u + 2u] = (uint8_t)((v >> 16u) & 0xFFu);
        buf[i * 4u + 3u] = (uint8_t)((v >> 24u) & 0xFFu);
    }

    uint32_t hash = fq_crc32(buf, sizeof(buf));
    TEST_ASSERT_EQUAL_UINT32(0x7B1900A6u, hash);
}

/* DET-NT-4b: Running the identical sequence twice must yield identical hashes
 * (proves no hidden mutable global state in either module). */
static void test_10k_hash_is_reproducible(void)
{
    static uint8_t buf_a[10000u * 4u];
    static uint8_t buf_b[10000u * 4u];

    fq_prng_t rng;

    fq_prng_init(&rng, 1u);
    for (uint32_t i = 0u; i < 10000u; i++) {
        uint32_t v = fq_prng_next(&rng);
        buf_a[i * 4u + 0u] = (uint8_t)((v >>  0u) & 0xFFu);
        buf_a[i * 4u + 1u] = (uint8_t)((v >>  8u) & 0xFFu);
        buf_a[i * 4u + 2u] = (uint8_t)((v >> 16u) & 0xFFu);
        buf_a[i * 4u + 3u] = (uint8_t)((v >> 24u) & 0xFFu);
    }

    fq_prng_init(&rng, 1u);
    for (uint32_t i = 0u; i < 10000u; i++) {
        uint32_t v = fq_prng_next(&rng);
        buf_b[i * 4u + 0u] = (uint8_t)((v >>  0u) & 0xFFu);
        buf_b[i * 4u + 1u] = (uint8_t)((v >>  8u) & 0xFFu);
        buf_b[i * 4u + 2u] = (uint8_t)((v >> 16u) & 0xFFu);
        buf_b[i * 4u + 3u] = (uint8_t)((v >> 24u) & 0xFFu);
    }

    uint32_t hash_a = fq_crc32(buf_a, sizeof(buf_a));
    uint32_t hash_b = fq_crc32(buf_b, sizeof(buf_b));
    TEST_ASSERT_EQUAL_UINT32(hash_a, hash_b);
}

int main(void)
{
    test_10k_prng_crc32_hash();
    test_10k_hash_is_reproducible();
    return 0;
}
