/**
 * test_prng.c — Feature/happy-path tests for fq_prng (Phase B: FEATURE RED).
 *
 * Tests frozen 10-iteration sequences for seeds 1, 42, and 0xDEADBEEF.
 * These values are mathematically derived from the xorshift32 algorithm
 * (state ^= state<<13; state ^= state>>17; state ^= state<<5) and pinned
 * as literals so any future change to the PRNG algorithm breaks CI immediately.
 *
 * Also tests: range distribution, and range return semantics.
 */

#include <stdint.h>
#include "test_assert.h"
#include "prng.h"

/* ---------------------------------------------------------------------------
 * Frozen sequence tables — generated by reference Python implementation.
 * xorshift32: state ^= (state<<13); state ^= (state>>17); state ^= (state<<5)
 * seed=0 is mapped to seed=1 per zero-seed deadlock guard.
 * ---------------------------------------------------------------------------*/

/* Seed 1 — first 10 outputs */
static const uint32_t k_seq_seed1[10] = {
    0x00042021u,  /* 270369    */
    0x04080601u,  /* 67634689  */
    0x9DCCA8C5u,  /* 2647435461*/
    0x1255994Fu,  /* 307599695 */
    0x8EF917D1u,  /* 2398689233*/
    0x2C6F5BD0u,  /* 745495504 */
    0x25B2331Au,  /* 632435482 */
    0x19F91CB2u,  /* 435756210 */
    0x77877125u,  /* 2005365029*/
    0xADD02374u   /* 2916098932*/
};

/* Seed 42 — first 10 outputs */
static const uint32_t k_seq_seed42[10] = {
    0x00AD4528u,  /* 11355432  */
    0xA90A34ACu,  /* 2836018348*/
    0x1C67AF03u,  /* 476557059 */
    0xD970C3C0u,  /* 3648046016*/
    0xE01CCBC4u,  /* 3759983556*/
    0x55EA99B6u,  /* 1441438134*/
    0xDD5701D8u,  /* 3713466840*/
    0x90EFF2AEu,  /* 2431644334*/
    0xB9FABB93u,  /* 3120216979*/
    0x3F9D3637u   /* 1067267639*/
};

/* Seed 0xDEADBEEF — first 10 outputs */
static const uint32_t k_seq_seeddb[10] = {
    0x477D20B7u,  /* 1199382711*/
    0x8E1D9142u,  /* 2384302402*/
    0xBA8C2458u,  /* 3129746520*/
    0xFEE0503Bu,  /* 4276113467*/
    0x680E0348u,  /* 1745748808*/
    0xA48DB81Bu,  /* 2760751131*/
    0x6254EA5Cu,  /* 1649732188*/
    0x1CFDAFB3u,  /* 486387635 */
    0x8878FDF6u,  /* 2289630710*/
    0x6F08B4B5u   /* 1862841525*/
};

/* PRNG-NT-5: Frozen sequence for seed=1 */
static void test_sequence_seed_1(void)
{
    fq_prng_t rng;
    fq_prng_init(&rng, 1u);
    for (int i = 0; i < 10; i++) {
        uint32_t v = fq_prng_next(&rng);
        TEST_ASSERT_EQUAL_UINT32(k_seq_seed1[i], v);
    }
}

/* PRNG-NT-5: Frozen sequence for seed=42 */
static void test_sequence_seed_42(void)
{
    fq_prng_t rng;
    fq_prng_init(&rng, 42u);
    for (int i = 0; i < 10; i++) {
        uint32_t v = fq_prng_next(&rng);
        TEST_ASSERT_EQUAL_UINT32(k_seq_seed42[i], v);
    }
}

/* PRNG-NT-5: Frozen sequence for seed=0xDEADBEEF */
static void test_sequence_seed_deadbeef(void)
{
    fq_prng_t rng;
    fq_prng_init(&rng, 0xDEADBEEFu);
    for (int i = 0; i < 10; i++) {
        uint32_t v = fq_prng_next(&rng);
        TEST_ASSERT_EQUAL_UINT32(k_seq_seeddb[i], v);
    }
}

/* Range test: all values in [0, 10] over 1000 iterations */
static void test_range_stays_in_bounds(void)
{
    fq_prng_t rng;
    fq_prng_init(&rng, 1u);
    for (int i = 0; i < 1000; i++) {
        uint32_t v = fq_prng_range(&rng, 0u, 10u);
        TEST_ASSERT_TRUE(v <= 10u);
    }
}

/* Range test: [5, 15] — all values within bounds */
static void test_range_offset_bounds(void)
{
    fq_prng_t rng;
    fq_prng_init(&rng, 42u);
    for (int i = 0; i < 1000; i++) {
        uint32_t v = fq_prng_range(&rng, 5u, 15u);
        TEST_ASSERT_TRUE(v >= 5u);
        TEST_ASSERT_TRUE(v <= 15u);
    }
}

/* Determinism: same seed always produces same first value */
static void test_determinism_same_seed_same_first_value(void)
{
    fq_prng_t rng_a;
    fq_prng_t rng_b;
    fq_prng_init(&rng_a, 12345u);
    fq_prng_init(&rng_b, 12345u);
    TEST_ASSERT_EQUAL_UINT32(fq_prng_next(&rng_a), fq_prng_next(&rng_b));
}

int main(void)
{
    test_sequence_seed_1();
    test_sequence_seed_42();
    test_sequence_seed_deadbeef();
    test_range_stays_in_bounds();
    test_range_offset_bounds();
    test_determinism_same_seed_same_first_value();
    return 0;
}
