/**
 * progression.c — FiestaQuest Effective Stat Curve implementation.
 *
 * Frozen 256-entry lookup table. No floating-point at runtime.
 * See progression.h for formula, pinned values, and contract.
 *
 * Table generation (offline Python, not compiled):
 *   import math
 *   [round(10 * math.log(i + 1) / math.log(11)) for i in range(256)]
 */

#include "progression.h"

/**
 * k_effective_stat_table — Frozen logarithmic stat scaling table.
 *
 * Index is raw stat value (0-255). Value is effective stat (0-23).
 * Monotonically non-decreasing. Generated by offline Python script.
 * DO NOT modify without re-generating from the formula and updating
 * all pinned test assertions in test_progression.c.
 */
static const uint8_t k_effective_stat_table[256] = {
    /*   0- 15 */   0,  3,  5,  6,  7,  7,  8,  9,  9, 10, 10, 10, 11, 11, 11, 12,
    /*  16- 31 */  12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14,
    /*  32- 47 */  15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16,
    /*  48- 63 */  16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
    /*  64- 79 */  17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
    /*  80- 95 */  18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
    /*  96-111 */  19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20,
    /* 112-127 */  20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    /* 128-143 */  20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21,
    /* 144-159 */  21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
    /* 160-175 */  21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22,
    /* 176-191 */  22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
    /* 192-207 */  22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
    /* 208-223 */  22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23,
    /* 224-239 */  23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
    /* 240-255 */  23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23
};

/* STAT-NT-5: Compile-time size assertion — must be exactly 256 bytes */
_Static_assert(sizeof(k_effective_stat_table) == 256u,
    "k_effective_stat_table must have exactly 256 entries (one per uint8_t value)");

uint8_t fq_effective_stat(uint8_t raw)
{
    return k_effective_stat_table[raw];
}
