#!/usr/bin/env python3
"""
sprite_to_c.py — FiestaQuest Phase 17 Asset Pipeline

Converts a PNG sprite sheet into a C header containing packed 1-bit
uint8_t arrays suitable for fq_blit_sprite().

Bit packing convention (matches fq_fb_set_pixel MSB-first):
  - Each row of pixels is stored MSB-first.
  - ceil(cell_width / 8) bytes per row.
  - Trailing bits in the last byte of each row are zero-padded.

Polarity:
  - Default (sprite mode): dark pixel on light background.
    A pixel is SET (=1/black on e-paper) when:
      alpha >= 128  AND  (R+G+B)/3 < 128

  - Inverted mode (--invert flag, used for fonts): white glyph on
    transparent background.
    A pixel is SET (=1/black on e-paper) when:
      alpha >= 128  AND  (R+G+B)/3 > 128

Usage:
  python3 tools/sprite_to_c.py \\
      <png_path> <cell_w> <cell_h> <cols> <rows> \\
      <output_header> <array_prefix> [--invert]

Example:
  python3 tools/sprite_to_c.py \\
      assets/Characters/32x32-Charset.png 32 32 8 21 \\
      components/presentation/include/sprites/sprite_chars.h sprite_char
"""

import sys
import os
import math
import argparse


# ---------------------------------------------------------------------------
# Core helper functions (mirror the reference implementations in the bound
# tests so the same logic is tested and used).
# ---------------------------------------------------------------------------

def pixel_stride(width):
    """Return the number of bytes per row: ceil(width / 8)."""
    return math.ceil(width / 8)


def pixel_is_set(r, g, b, a, invert=False):
    """
    Return 1 if this pixel should be SET (black on e-paper), 0 otherwise.

    Sprite polarity (invert=False):
      dark pixel on light/transparent background → brightness < 128 = SET.

    Font polarity (invert=True):
      white glyph on transparent background → brightness > 128 = SET.

    In both cases: alpha < 128 → transparent → always 0.
    """
    if a < 128:
        return 0
    brightness = (r + g + b) // 3
    if invert:
        return 1 if brightness > 128 else 0
    else:
        return 1 if brightness < 128 else 0


def pack_row(pixel_bits):
    """
    Pack a list of 0/1 bits into bytes, MSB first.
    Returns a bytes object of length ceil(len(pixel_bits) / 8).
    Trailing bits in the last byte are zero-padded.
    """
    result = []
    width = len(pixel_bits)
    stride = pixel_stride(width)
    for byte_idx in range(stride):
        byte_val = 0
        for bit_offset in range(8):
            col = byte_idx * 8 + bit_offset
            if col < width and pixel_bits[col]:
                byte_val |= (0x80 >> bit_offset)
        result.append(byte_val)
    return bytes(result)


def extract_cell_bitmap(img_pixels, img_width, cell_x, cell_y,
                        cell_w, cell_h, invert=False):
    """
    Extract a cell from an image (given as a flat list of (R,G,B,A) tuples
    in row-major order) and return the packed 1-bit bitmap as bytes.

    cell_x, cell_y: top-left pixel coordinate of the cell in the source image.
    cell_w, cell_h: dimensions of the cell.
    img_width: pixel width of the source image (for address calculation).
    """
    out = []
    for row in range(cell_h):
        row_bits = []
        for col in range(cell_w):
            px_x = cell_x + col
            px_y = cell_y + row
            idx = px_y * img_width + px_x
            r, g, b, a = img_pixels[idx]
            row_bits.append(pixel_is_set(r, g, b, a, invert=invert))
        out.extend(pack_row(row_bits))
    return bytes(out)


# ---------------------------------------------------------------------------
# C code generation
# ---------------------------------------------------------------------------

RODATA_WARNING = """\
/*
 * WARNING: This header contains static const arrays. Include it in exactly
 * ONE translation unit per link target to avoid RODATA duplication.
 * Multiple includes will compile without error but silently double flash usage.
 */
"""

HEADER_BANNER = """\
/**
 * {filename} — Auto-generated by tools/sprite_to_c.py
 *
 * Source : {source_png}
 * Grid   : {cols} cols × {rows} rows, {cell_w}×{cell_h} px per cell
 * Polarity: {polarity}
 * Total  : {total_sprites} sprites, {total_bytes} bytes of bitmap data
 *
 * DO NOT EDIT — regenerate with:
 *   python3 tools/sprite_to_c.py {args_echo}
 *
 * Bit packing: MSB-first, ceil({cell_w}/8) = {stride} bytes per row.
 * Matches fq_fb_set_pixel() MSB-first convention.
 *
 * Each entry in {prefix}_TABLE is a fq_sprite_t pointing to its bitmap.
 */
"""

ONCE_GUARD_OPEN = """\
#ifndef {guard}
#define {guard}

#include <stdint.h>
#include "fq_sprite.h"

"""

ONCE_GUARD_CLOSE = """\
#endif /* {guard} */
"""


def c_array_name(prefix, row, col):
    return "{}_r{:02d}_c{:02d}".format(prefix, row, col)


def bytes_to_c_hex(data, indent="    "):
    """Format a bytes object as comma-separated 0xNN hex literals."""
    items = ["0x{:02X}U".format(b) for b in data]
    lines = []
    chunk = 16
    for i in range(0, len(items), chunk):
        lines.append(indent + ", ".join(items[i:i+chunk]))
    return ",\n".join(lines)


def generate_sprite_header(png_path, cell_w, cell_h, cols, rows,
                           output_path, prefix, invert=False):
    """
    Main entry point: open the PNG, extract all cells, write the C header.
    Returns a dict with stats for reporting.
    """
    try:
        from PIL import Image
    except ImportError:
        print("ERROR: Pillow is required. Install with: pip install Pillow",
              file=sys.stderr)
        sys.exit(1)

    img = Image.open(png_path).convert("RGBA")
    img_w, img_h = img.size
    expected_w = cell_w * cols
    expected_h = cell_h * rows
    if img_w < expected_w or img_h < expected_h:
        print(
            "ERROR: Image {}×{} is smaller than the grid {}×{}.".format(
                img_w, img_h, expected_w, expected_h),
            file=sys.stderr)
        sys.exit(1)

    pixels = list(img.getdata())  # flat list of (R,G,B,A) tuples
    stride = pixel_stride(cell_w)
    polarity_str = ("font/inverted: white pixel → SET"
                    if invert else
                    "sprite: dark pixel → SET")
    total_sprites = cols * rows
    total_bytes = total_sprites * stride * cell_h

    # --- Ensure output directory exists ---
    out_dir = os.path.dirname(output_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    filename = os.path.basename(output_path)
    guard = filename.upper().replace(".", "_").replace("-", "_").replace("/", "_")
    # args echo string for the regeneration comment
    args_echo = "{} {} {} {} {} {} {}{}".format(
        png_path, cell_w, cell_h, cols, rows,
        output_path, prefix,
        " --invert" if invert else "")

    with open(output_path, "w") as f:
        # --- File header banner ---
        f.write(HEADER_BANNER.format(
            filename=filename,
            source_png=os.path.relpath(png_path),
            cols=cols, rows=rows,
            cell_w=cell_w, cell_h=cell_h,
            polarity=polarity_str,
            total_sprites=total_sprites,
            total_bytes=total_bytes,
            stride=stride,
            prefix=prefix,
            args_echo=args_echo,
        ))

        # --- RODATA duplication warning ---
        f.write(RODATA_WARNING)

        f.write(ONCE_GUARD_OPEN.format(guard=guard))

        # --- Per-cell bitmap arrays ---
        cell_names = []
        for row in range(rows):
            for col in range(cols):
                cell_x = col * cell_w
                cell_y = row * cell_h
                bitmap = extract_cell_bitmap(
                    pixels, img_w, cell_x, cell_y, cell_w, cell_h,
                    invert=invert)
                name = c_array_name(prefix, row, col)
                cell_names.append(name)
                f.write(
                    "static const uint8_t {}[{}] = {{\n".format(
                        name, len(bitmap)))
                f.write(bytes_to_c_hex(bitmap))
                f.write("\n};\n\n")

        # --- Index table ---
        f.write("/* ── Sprite index table ──────────────────────────────────── */\n\n")
        f.write("static const fq_sprite_t {}_TABLE[{}] = {{\n".format(
            prefix.upper(), total_sprites))
        idx = 0
        for row in range(rows):
            f.write("    /* row {:02d} */\n".format(row))
            for col in range(cols):
                name = cell_names[idx]
                f.write(
                    "    {{ .data = {}, .width = {}u, .height = {}u }},\n".format(
                        name, cell_w, cell_h))
                idx += 1
        f.write("};\n\n")

        f.write(ONCE_GUARD_CLOSE.format(guard=guard))

    return {
        "sprites": total_sprites,
        "bytes": total_bytes,
        "output": output_path,
    }


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Convert a PNG sprite sheet to a packed 1-bit C header.")
    parser.add_argument("png_path",       help="Path to source PNG")
    parser.add_argument("cell_w",  type=int, help="Cell width in pixels")
    parser.add_argument("cell_h",  type=int, help="Cell height in pixels")
    parser.add_argument("cols",    type=int, help="Number of columns")
    parser.add_argument("rows",    type=int, help="Number of rows")
    parser.add_argument("output_header", help="Output C header path")
    parser.add_argument("array_prefix",  help="Prefix for C identifiers")
    parser.add_argument("--invert", action="store_true",
                        help="Invert polarity: white pixel = SET (for fonts)")
    args = parser.parse_args()

    stats = generate_sprite_header(
        png_path=args.png_path,
        cell_w=args.cell_w,
        cell_h=args.cell_h,
        cols=args.cols,
        rows=args.rows,
        output_path=args.output_header,
        prefix=args.array_prefix,
        invert=args.invert,
    )
    print("sprite_to_c: wrote {} sprites ({} bytes) → {}".format(
        stats["sprites"], stats["bytes"], stats["output"]))


if __name__ == "__main__":
    main()
